spring:
  application:
    name: springboot-with-aws-lambda
  security:
    user:
      name: user
      password: password
      roles: USER
  cloud:
    aws:
      credentials:
        profile:
          name: default
      #secret-key: ${SECRET_KEY}
      #access-key: ${ACCESS_KEY}
      region:
        static: eu-north-1
  main:
    lazy-initialization: true

logging:
  level:
    org.springframework.security: WARN
    web: WARN